[deps]
CodonMolecularEvolution = "6511b2a3-0bb8-4def-a118-560a7e125e34"
FASTX = "c2308a5c-f048-11e8-3e8a-31650f418d12"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
MolecularEvolution = "9f975960-e239-4209-8aa0-3d3ad5a82892"
Phylo = "aea672f4-3940-5932-aa44-993d1c3ff149"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
